version: 2.1

orbs:
  unity: game-ci/unity@x.y

workflows:
  create-unity-activation-file:
      jobs:
        - unity/create-activation-file:
            editor_version: '2022.3.10f1'
  build-unity-project:
    jobs:
      - unity/build:
          name: 'build-windows-mono'
          step-name: 'Build StandaloneWindows64'
          unity-license-var-name: 'UNITY_ENCODED_LICENSE'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/windows-2022'
            target_platform: 'windows-mono'
            editor_version: '2022.3.10f1'
            resource_class: 'large'
          project-path: '.'
          build-target: StandaloneWindows64
          compress: true
          context: unity
          build-method: 'SuperUnityBuild.BuildTool.BuildCLI.PerformBuild'